In [3]:
from urllib.request import urlopen
import json
import pandas as pd

In [4]:

uri = """https://api.bar-rts.com/replays?page=1&limit=24&hasBots=false&endedNormally=true&players=%5BTZN%5DClyret"""

In [5]:
data = json.loads(urlopen(uri).read().decode("utf-8"))

In [19]:
with open("data.json", "w") as outfile:
    json.dump(data['data'],outfile,indent=4, sort_keys=True)

In [43]:
df = pd.json_normalize(data["data"]) #put json inside a dataframe, ["AllyTeams", "Players"]

In [44]:
df

,id,startTime,durationMs,AllyTeams,Map.fileName,Map.scriptName
0,1605a064c1ca5c832f44d4ce5a4e15f8,2023-07-01T10:51:02.000Z,2925833,"[{'winningTeam': True, 'Players': [{'name': '[...",ice_scream_v2.5,Ice Scream v2.5
1,7efc9f64d2bfc1c98e4fdd32b182a672,2023-07-01T10:14:22.000Z,1599333,"[{'winningTeam': False, 'Players': [{'name': '...",white_fire_remake_1.2,White Fire Remake 1.2
2,6bf39f64db3e124c75d74fe904cdbccb,2023-07-01T09:35:39.000Z,1735967,"[{'winningTeam': True, 'Players': [{'name': '[...",ascendancy_v2.0,Ascendancy v2.0
3,fdee9f646f55590b5f4b351b2e4ccea9,2023-07-01T09:16:45.000Z,765100,"[{'winningTeam': True, 'Players': [{'name': 'H...",ascendancy_v2.0,Ascendancy v2.0
4,eeea9f64cd02d71f0fc92a8eab2ada3c,2023-07-01T08:59:26.000Z,616667,"[{'winningTeam': True, 'Players': [{'name': 'H...",eight_horses_1.2,Eight Horses 1.2
5,cee19f64e1b999cf1c0a212b4c42e744,2023-07-01T08:20:30.000Z,1508833,"[{'winningTeam': True, 'Players': [{'name': 'M...",koom_valley_3_3.1,Koom Valley 3 3.1
6,b9db9f649a61cee00e8a4500f794573c,2023-07-01T07:54:33.000Z,1204900,"[{'winningTeam': False, 'Players': [{'name': '...",bismuth_valley_v2.2,Bismuth Valley v2.2
7,a6d49f647fe9bcd63ee1390163bca0da,2023-07-01T07:24:22.000Z,1393700,"[{'winningTeam': True, 'Players': [{'name': 'M...",flats_and_forests_v2.1,Flats and Forests v2.1
8,3ecf9f64f0e481092463824bb96034b6,2023-07-01T07:01:18.000Z,976600,"[{'winningTeam': False, 'Players': [{'name': '...",Rosetta1.4,Rosetta 1.4
9,8ac19f64a662a7f4873ce6e59e6cf399,2023-07-01T06:02:50.000Z,1357367,"[{'winningTeam': False, 'Players': [{'name': '...",theta_crystals_1.0,Theta Crystals 1.0
10,51bb9f64e100570e613fb36b0476253d,2023-07-01T05:36:17.000Z,1376167,"[{'winningTeam': False, 'Players': [{'name': '...",shallow_straits_v1,Shallow Straits v1
11,3cb79f6474012b2c8dc53f6d90fe0bfe,2023-07-01T05:18:52.000Z,637667,"[{'winningTeam': True, 'Players': [{'name': '[...",seths_ravine_remake_1.3,Seths Ravine Remake 1.3
12,6fb39f64f800b735b846f98834f03262,2023-07-01T05:02:39.000Z,711067,"[{'winningTeam': False, 'Players': [{'name': '...",red_comet_remake_1.8,Red Comet Remake 1.8
13,40b09f641f4ee2100e66214618179515,2023-07-01T04:49:04.000Z,559300,"[{'winningTeam': True, 'Players': [{'name': '[...",comet_catcher_remake_1.8,Comet Catcher Remake 1.8
14,19ae9f649b4aefa57bd05e63c876759d,2023-07-01T04:39:53.000Z,304033,"[{'winningTeam': False, 'Players': [{'name': '...",faster_than_light_1.1,Faster Than Light 1.1
15,81ab9f6412ec3e58ba1d5599daf4ae7f,2023-07-01T04:28:49.000Z,419033,"[{'winningTeam': False, 'Players': [{'name': '...",red_comet_remake_1.8,Red Comet Remake 1.8
16,34a89f647b270b0b975c8c6f4c5b6e54,2023-07-01T04:14:44.000Z,597267,"[{'winningTeam': False, 'Players': [{'name': '...",ravaged_remake_v1.2,Ravaged Remake v1.2
17,48a69f64f824a1b6e59689d1ab996f55,2023-07-01T04:06:32.000Z,353633,"[{'winningTeam': True, 'Players': [{'name': '[...",ravaged_remake_v1.2,Ravaged Remake v1.2
18,9da39f64b29cc8e948e47ae3698d40a1,2023-07-01T03:55:09.000Z,538467,"[{'winningTeam': True, 'Players': [{'name': '[...",ravaged_remake_v1.2,Ravaged Remake v1.2
19,1d929f64d2fc194edcba15bdfbb866a0,2023-07-01T02:40:29.000Z,254300,"[{'winningTeam': False, 'Players': [{'name': '...",shallow_straits_v1,Shallow Straits v1
20,8e8d9f641ef22fea9fe3a1529d1e963f,2023-07-01T02:21:02.000Z,806067,"[{'winningTeam': True, 'Players': [{'name': '[...",zed_remake_3.3,Zed Remake 3.3
21,443c9e6476559d72c4c06274e9f47195,2023-06-30T02:21:56.000Z,1095833,"[{'winningTeam': False, 'Players': [{'name': '...",bismuth_valley_v2.2,Bismuth Valley v2.2
22,8f319e641ce08a202e2a6a4bf9dba088,2023-06-30T01:36:15.000Z,2240733,"[{'winningTeam': True, 'Players': [{'name': '[...",koom_valley_3_3.1,Koom Valley 3 3.1
23,c02a9e64c743d560dd209ac0e457acae,2023-06-30T01:07:12.000Z,1286700,"[{'winningTeam': False, 'Players': [{'name': '...",Rosetta1.4,Rosetta 1.4

In [45]:
df_AllyTeams = df['AllyTeams'].explode().apply(pd.Series)

In [46]:
df_AllyTeams

    winningTeam                                            Players AIs
0          True  [{'name': '[8D]'}, {'name': 'Unicorn_cats'}, {...  []
0         False  [{'name': 'EmperorGlass'}, {'name': 'Litschi'}...  []
1         False  [{'name': 'EmperorGlass'}, {'name': 'Isy'}, {'...  []
1          True  [{'name': 'HellsHound'}, {'name': 'FNS'}, {'na...  []
2          True  [{'name': '[TZN]Clyret'}, {'name': 'Doushibag'...  []
2         False  [{'name': 'EXZoPyroMathic'}, {'name': 'Litschi...  []
3          True  [{'name': 'HellsHound'}, {'name': 'Rathim'}, {...  []
3         False  [{'name': 'Nezah'}, {'name': 'r77feed'}, {'nam...  []
4          True  [{'name': 'HellsHound'}, {'name': 'badbot'}, {...  []
4         False  [{'name': 'FNS'}, {'name': 'spoderfriend'}, {'...  []
5          True  [{'name': 'MomsBoyToy'}, {'name': 'badbot'}, {...  []
5         False  [{'name': 'orange_state'}, {'name': 'Karolson'...  []
6         False  [{'name': 'MomsBoyToy'}, {'name': 'Crabscratch...  []
6          True  [{'name': 'Nezah'}, {'name': 'StarDoM'}, {'nam...  []
7          True  [{'name': 'MomsBoyToy'}, {'name': 'Crabscratch...  []
7         False  [{'name': 'Nezah'}, {'name': 'Kuchy'}, {'name'...  []
8         False  [{'name': 'MomsBoyToy'}, {'name': 'badbot'}, {...  []
8          True  [{'name': 'EmperorGlass'}, {'name': 'avocado'}...  []
9         False                          [{'name': '[TZN]Clyret'}]  []
9          True                              [{'name': 'StarDoM'}]  []
10        False                          [{'name': '[TZN]Clyret'}]  []
10         True                              [{'name': 'StarDoM'}]  []
11         True                          [{'name': '[TZN]Clyret'}]  []
11        False                          [{'name': '[eVo]Contra'}]  []
12        False                          [{'name': '[TZN]Clyret'}]  []
12         True                              [{'name': 'StarDoM'}]  []
13         True                          [{'name': '[TZN]Clyret'}]  []
13        False                              [{'name': 'StarDoM'}]  []
14        False                          [{'name': '[eVo]Contra'}]  []
14         True                          [{'name': '[TZN]Clyret'}]  []
15        False                          [{'name': '[eVo]Contra'}]  []
15         True                          [{'name': '[TZN]Clyret'}]  []
16        False                          [{'name': '[eVo]Contra'}]  []
16         True                          [{'name': '[TZN]Clyret'}]  []
17         True                          [{'name': '[eVo]Contra'}]  []
17        False                          [{'name': '[TZN]Clyret'}]  []
18         True                          [{'name': '[eVo]Contra'}]  []
18        False                          [{'name': '[TZN]Clyret'}]  []
19        False                              [{'name': 'StarDoM'}]  []
19         True                          [{'name': '[TZN]Clyret'}]  []
20         True                          [{'name': '[TZN]Clyret'}]  []
20        False                              [{'name': 'StarDoM'}]  []
21        False  [{'name': 'MomsBoyToy'}, {'name': 'Nayss'}, {'...  []
21         True  [{'name': 'Volshok'}, {'name': 'JRExp'}, {'nam...  []
22         True  [{'name': '[TZN]Clyret'}, {'name': 'Nayss'}, {...  []
22        False  [{'name': 'TNTremor'}, {'name': 'laughing'}, {...  []
23        False  [{'name': '[TZN]Clyret'}, {'name': 'spj57'}, {...  []
23         True  [{'name': 'I_AM_MEGATRON'}, {'name': 'rtx'}, {...  []

In [48]:
df_Players = df_AllyTeams['Players'].explode().apply(pd.Series)

In [49]:
df_Players

             name
0            [8D]
0    Unicorn_cats
0          Taichu
0       Mixail007
0   I_AM_MEGATRON
..            ...
23       Rangoran
23          Nayss
23        avocado
23         deyv1d
23        wrong48

[216 rows x 1 columns]

In [70]:
# Get the winning team and count the number of wins
win_count = 0
matches = {}
for match in data['data']:
    for team in match['AllyTeams']:
        if team['winningTeam']:
            for player in team['Players']:
                if player['name'] == "[TZN]Clyret":
                    matches = {**matches, **{match['id']:match}}

In [71]:
matches

{'6bf39f64db3e124c75d74fe904cdbccb': {'id': '6bf39f64db3e124c75d74fe904cdbccb',
  'startTime': '2023-07-01T09:35:39.000Z',
  'durationMs': 1735967,
  'Map': {'fileName': 'ascendancy_v2.0', 'scriptName': 'Ascendancy v2.0'},
  'AllyTeams': [{'winningTeam': True,
    'Players': [{'name': '[TZN]Clyret'},
     {'name': 'Doushibag'},
     {'name': 'HotshotGG'},
     {'name': 'Unicorn_cats'},
     {'name': 'FNS'},
     {'name': 'NuTCrAcK'},
     {'name': 'Isy'},
     {'name': 'Nezah'}],
    'AIs': []},
   {'winningTeam': False,
    'Players': [{'name': 'EXZoPyroMathic'},
     {'name': 'Litschi'},
     {'name': 'Mixail007'},
     {'name': 'Rathim'},
     {'name': 'Nostradamus'},
     {'name': 'StarDoM'},
     {'name': 'HellsHound'},
     {'name': 'Addas'}],
    'AIs': []}]},
 'b9db9f649a61cee00e8a4500f794573c': {'id': 'b9db9f649a61cee00e8a4500f794573c',
  'startTime': '2023-07-01T07:54:33.000Z',
  'durationMs': 1204900,
  'Map': {'fileName': 'bismuth_valley_v2.2',
   'scriptName': 'Bismuth Valley v2.2'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': 'MomsBoyToy'},
     {'name': 'Crabscratch'},
     {'name': 'Doushibag'},
     {'name': 'Demondred'},
     {'name': 'orange_state'},
     {'name': 'Karolson'},
     {'name': 'Daymus'},
     {'name': 'Caliburn'}],
    'AIs': []},
   {'winningTeam': True,
    'Players': [{'name': 'Nezah'},
     {'name': 'StarDoM'},
     {'name': 'avocado'},
     {'name': 'badbot'},
     {'name': 'Luna777'},
     {'name': 'Skye02'},
     {'name': '[TZN]Clyret'},
     {'name': 'FNS'}],
    'AIs': []}]},
 '3ecf9f64f0e481092463824bb96034b6': {'id': '3ecf9f64f0e481092463824bb96034b6',
  'startTime': '2023-07-01T07:01:18.000Z',
  'durationMs': 976600,
  'Map': {'fileName': 'Rosetta1.4', 'scriptName': 'Rosetta 1.4'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': 'MomsBoyToy'},
     {'name': 'badbot'},
     {'name': 'TrollHardGoPro'},
     {'name': 'Demondred'},
     {'name': 'FNS'},
     {'name': 'Kuchy'},
     {'name': 'Skye02'},
     {'name': 'Caliburn'}],
    'AIs': []},
   {'winningTeam': True,
    'Players': [{'name': 'EmperorGlass'},
     {'name': 'avocado'},
     {'name': 'Nezah'},
     {'name': 'Crabscratch'},
     {'name': 'Doushibag'},
     {'name': 'Daymus'},
     {'name': '[TZN]Clyret'},
     {'name': 'durtyrandy'}],
    'AIs': []}]},
 '3cb79f6474012b2c8dc53f6d90fe0bfe': {'id': '3cb79f6474012b2c8dc53f6d90fe0bfe',
  'startTime': '2023-07-01T05:18:52.000Z',
  'durationMs': 637667,
  'Map': {'fileName': 'seths_ravine_remake_1.3',
   'scriptName': 'Seths Ravine Remake 1.3'},
  'AllyTeams': [{'winningTeam': True,
    'Players': [{'name': '[TZN]Clyret'}],
    'AIs': []},
   {'winningTeam': False, 'Players': [{'name': '[eVo]Contra'}], 'AIs': []}]},
 '40b09f641f4ee2100e66214618179515': {'id': '40b09f641f4ee2100e66214618179515',
  'startTime': '2023-07-01T04:49:04.000Z',
  'durationMs': 559300,
  'Map': {'fileName': 'comet_catcher_remake_1.8',
   'scriptName': 'Comet Catcher Remake 1.8'},
  'AllyTeams': [{'winningTeam': True,
    'Players': [{'name': '[TZN]Clyret'}],
    'AIs': []},
   {'winningTeam': False, 'Players': [{'name': 'StarDoM'}], 'AIs': []}]},
 '19ae9f649b4aefa57bd05e63c876759d': {'id': '19ae9f649b4aefa57bd05e63c876759d',
  'startTime': '2023-07-01T04:39:53.000Z',
  'durationMs': 304033,
  'Map': {'fileName': 'faster_than_light_1.1',
   'scriptName': 'Faster Than Light 1.1'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': '[eVo]Contra'}],
    'AIs': []},
   {'winningTeam': True, 'Players': [{'name': '[TZN]Clyret'}], 'AIs': []}]},
 '81ab9f6412ec3e58ba1d5599daf4ae7f': {'id': '81ab9f6412ec3e58ba1d5599daf4ae7f',
  'startTime': '2023-07-01T04:28:49.000Z',
  'durationMs': 419033,
  'Map': {'fileName': 'red_comet_remake_1.8',
   'scriptName': 'Red Comet Remake 1.8'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': '[eVo]Contra'}],
    'AIs': []},
   {'winningTeam': True, 'Players': [{'name': '[TZN]Clyret'}], 'AIs': []}]},
 '34a89f647b270b0b975c8c6f4c5b6e54': {'id': '34a89f647b270b0b975c8c6f4c5b6e54',
  'startTime': '2023-07-01T04:14:44.000Z',
  'durationMs': 597267,
  'Map': {'fileName': 'ravaged_remake_v1.2',
   'scriptName': 'Ravaged Remake v1.2'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': '[eVo]Contra'}],
    'AIs': []},
   {'winningTeam': True, 'Players': [{'name': '[TZN]Clyret'}], 'AIs': []}]},
 '1d929f64d2fc194edcba15bdfbb866a0': {'id': '1d929f64d2fc194edcba15bdfbb866a0',
  'startTime': '2023-07-01T02:40:29.000Z',
  'durationMs': 254300,
  'Map': {'fileName': 'shallow_straits_v1',
   'scriptName': 'Shallow Straits v1'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': 'StarDoM'}],
    'AIs': []},
   {'winningTeam': True, 'Players': [{'name': '[TZN]Clyret'}], 'AIs': []}]},
 '8e8d9f641ef22fea9fe3a1529d1e963f': {'id': '8e8d9f641ef22fea9fe3a1529d1e963f',
  'startTime': '2023-07-01T02:21:02.000Z',
  'durationMs': 806067,
  'Map': {'fileName': 'zed_remake_3.3', 'scriptName': 'Zed Remake 3.3'},
  'AllyTeams': [{'winningTeam': True,
    'Players': [{'name': '[TZN]Clyret'}],
    'AIs': []},
   {'winningTeam': False, 'Players': [{'name': 'StarDoM'}], 'AIs': []}]},
 '443c9e6476559d72c4c06274e9f47195': {'id': '443c9e6476559d72c4c06274e9f47195',
  'startTime': '2023-06-30T02:21:56.000Z',
  'durationMs': 1095833,
  'Map': {'fileName': 'bismuth_valley_v2.2',
   'scriptName': 'Bismuth Valley v2.2'},
  'AllyTeams': [{'winningTeam': False,
    'Players': [{'name': 'MomsBoyToy'},
     {'name': 'Nayss'},
     {'name': 'jjoliani'},
     {'name': 'APolygon'},
     {'name': 'Rangoran'},
     {'name': '[eSkilL]Andre'},
     {'name': 'spoderfriend'},
     {'name': '[DoR]Isildur[teh]'}],
    'AIs': []},
   {'winningTeam': True,
    'Players': [{'name': 'Volshok'},
     {'name': 'JRExp'},
     {'name': 'Screwish'},
     {'name': 'Luna777'},
     {'name': 'Elm'},
     {'name': 'deyv1d'},
     {'name': '[TZN]Clyret'},
     {'name': 'NerdyZen'}],
    'AIs': []}]},
 '8f319e641ce08a202e2a6a4bf9dba088': {'id': '8f319e641ce08a202e2a6a4bf9dba088',
  'startTime': '2023-06-30T01:36:15.000Z',
  'durationMs': 2240733,
  'Map': {'fileName': 'koom_valley_3_3.1', 'scriptName': 'Koom Valley 3 3.1'},
  'AllyTeams': [{'winningTeam': True,
    'Players': [{'name': '[TZN]Clyret'},
     {'name': 'Nayss'},
     {'name': 'jjoliani'},
     {'name': 'APolygon'},
     {'name': 'Volshok'},
     {'name': 'rtx'},
     {'name': 'avocado'},
     {'name': '[DoR]Isildur[teh]'}],
    'AIs': []},
   {'winningTeam': False,
    'Players': [{'name': 'TNTremor'},
     {'name': 'laughing'},
     {'name': 'Screwish'},
     {'name': 'NerdyZen'},
     {'name': 'Huggz'},
     {'name': 'deyv1d'},
     {'name': 'MomsBoyToy'},
     {'name': 'Rangoran'}],
    'AIs': []}]}}

In [69]:
win_count/len(data['data'])

0.5

In [25]:
data2 = [{'state': 'Florida',
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [35]:
result = pd.json_normalize(data2, 'counties', ['state', 'shortname',
                                           ['info', 'governor']])

In [36]:
result

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich